#ifndef __CALCULATOR_IDL__
#define __CALCULATOR_IDL__
module calculator {
	exception DivisionThroughZero {
		string message;
	 };

	interface Calculation {
		double add(in double nr1, in double nr2);
		double subtract(in double nr1, in double nr2);
		double multiply(in double nr1, in double nr2);
		double divide(in double nr1, in double nr2) raises (DivisionThroughZero);
	};
};
#endif  // __CALCULATOR_IDL__
